### PR TITLE
Update documentation

### PR DESCRIPTION
**Pull request by Zhi-704**

### CODE REVIEW

**Comment by Zhi-704** [comment]
Close #54

**Comment by Faris-Abulula** [comment]
Since `requirements.txt` changed to `local_requirements.txt`, the GitHub Actions should be changed accordingly. I'll fix it now

**Comment by Zhi-704** [comment]
Close #16

**Review by Faris-Abulula — APPROVED** [review]
Looks good, requirements has been sorted, readme file updated and bash scripts removed

**Pull request merged**
